# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Football News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Football News 
  pod 'Crashlytics'
  pod 'Firebase/Database' 
  pod 'Firebase/Core'
  pod 'youtube-ios-player-helper'
  pod 'URLEmbeddedView'
  pod 'NVActivityIndicatorView'
end
